#!/usr/bin/env python
#coding=utf-8

RULERS = {
    "cnr.cn": {
        "url": "http://tech.cnr.cn",
        "id": 4,
        "language": "1",
        "name": "中国广播网 央广科技",
        "rulers": set(["http://tech.cnr.cn/"]),
    },
    "xhby.net": {
        "url": "http://news.xhby.net/kj/",
        "id": 5,
        "language": "1",
        "name": "新华报业网—科技新闻",
        "rulers": set(["http://news.xhby.net/kj/"]),
    },
    "163.com": {
        "url": "http://tech.163.com",
        "id": 6,
        "language": "1",
        "name": "网易科技",
        "rulers": set(["http://tech.163.com/"]),
    },
    "engadget.com": {
        "url": "http://cn.engadget.com/category/news/",
        "id": 7,
        "language": "1",
        "name": "Engadget中国版—科技新闻",
        "rulers": set(["http://cn.engadget.com/category/news/"]),
    },
    "cnool.net": {
        "url": "http://news.cnool.net/c0-1-18/0-1-18.html",
        "id": 8,
        "language": "1",
        "name": "东方快讯 科技新闻",
        "rulers": set(["http://news.cnool.net/c0-1-18/"]),
    },
    "sohu.com": {
        "url": "http://it.sohu.com/",
        "id": 9,
        "language": "1",
        "name": "搜狐IT",
        "rulers": set(["http://it.sohu.com/"]),
    },
    "ifeng.com": {
        "url": "http://tech.ifeng.com/",
        "id": 10,
        "language": "1",
        "name": "凤凰科技",
        "rulers": set(["http://tech.ifeng.com/"]),
        "channel": "http://tech.ifeng.com/",
    },
    "qq.com": {
        "url": "http://tech.qq.com",
        "id": 11,
        "language": "1",
        "name": "腾讯科技",
        "rulers": set(["http://tech.qq.com/"]),
    },
    "yahoo.com": {
        "url": "http://tech.cn.yahoo.com/",
        "id": 12,
        "language": "1",
        "name": "雅虎科技",
        "rulers": set(["http://tech.cn.yahoo.com/"]),
    },
    "people.com.cn": {
        "url": "http://scitech.people.com.cn/",
        "id": 13,
        "language": "1",
        "name": "人民网—科技频道",
        "rulers": set(["http://scitech.people.com.cn/"]),
    },
    "china.com": {
        "url": "http://tech.china.com/",
        "id": 14,
        "language": "1",
        "name": "中华网 科技频道",
        "rulers": set(["http://tech.china.com/"]),
    },
    "news.cn": {
        "url": "http://www.news.cn/tech/index.htm",
        "id": 15,
        "language": "1",
        "name": "新华网 科技频道",
        "rulers": set(["http://www.news.cn/tech/index.htm"]),
    },
    "cntv.cn": {
        "url": "http://kejiao.cntv.cn/",
        "id": 16,
        "language": "1",
        "name": "央视网——科教频道",
        "rulers": set(["http://kejiao.cntv.cn/"]),
    },
    "techweb.com.cn": {
        "url": "http://www.techweb.com.cn/",
        "id": 17,
        "language": "1",
        "name": "TechWeb",
        "rulers": set(["http://www.techweb.com.cn/news/",
                       "http://www.techweb.com.cn/people/",
                       "http://www.techweb.com.cn/biz/",
                       "http://www.techweb.com.cn/special/",
                       "http://www.techweb.com.cn/ec/",
                       "http://www.techweb.com.cn/roll/",
                       "http://www.techweb.com.cn/chuangye/",
                       "http://www.techweb.com.cn/geek/"]),
    },
    "bianews.com": {
        "url": "http://www.bianews.com/",
        "id": 18,
        "language": "1",
        "name": "鞭牛士",
        "rulers": set(["http://www.bianews.com/", "http://bianews.com/"]),
    },
    "chinabyte.com": {
        "url": "http://www.chinabyte.com/",
        "id": 19,
        "language": "1",
        "name": "比特网",
        "rulers": set(["http://www.chinabyte.com/",
                       "http://news.chinabyte.com",
                       "http://e.chinabyte.com",
                       "http://cloud.chinabyte.com",
                       "http://info.chinabyte.com",
                       "http://mi.chinabyte.com",
                       "http://nbpc.chinabyte.com"]),
    },
    "leiphone.com": {
        "url": "http://www.leiphone.com/",
        "id": 20,
        "language": "1",
        "name": "雷锋网",
        "rulers": set(["http://www.leiphone.com/c-app/",
                       "http://www.leiphone.com/review/",
                       "http://www.leiphone.com/a-eye/",
                       "http://www.leiphone.com/special/",
                       "http://www.leiphone.com/opinion/",
                       "http://www.leiphone.com/video/"]),
    },
    "iheima.com": {
        "url": "http://www.iheima.com/",
        "id": 21,
        "language": "1",
        "name": "i黑马",
        "rulers": set(["http://www.iheima.com/for-inspiration/",
                       "http://www.iheima.com/evaluation/",
                       "http://www.iheima.com/qnews/",
                       "http://www.iheima.com/shuzhai/",
                       "http://www.iheima.com/zhuanlan/",
                       "http://www.iheima.com/top/",
                       "http://www.iheima.com/heima/"]),
    },
    "tmtpost.com": {
        "url": "http://www.tmtpost.com/",
        "id": 22,
        "language": "1",
        "name": "钛媒体",
        "rulers": set(["http://www.tmtpost.com/dig-into/",
                       "http://www.tmtpost.com/column/"]),
    },
    "newhua.com": {
        "url": "http://news.newhua.com/",
        "id": 23,
        "language": "1",
        "name": "牛华网——新闻中心",
        "rulers": set(["http://news.newhua.com/"]),
    },
    "kuailiyu.com": {
        "url": "http://www.kuailiyu.com/",
        "id": 24,
        "language": "1",
        "name": "快鲤鱼",
        "rulers": set(["http://www.kuailiyu.com/"]),
    },
    "hexun.com": {
        "url": "http://tech.hexun.com/",
        "id": 25,
        "language": "1",
        "name": "和讯科技",
        "rulers": set(["http://tech.hexun.com/"]),
    },
    "china.com.cn": {
        "url": "http://science.china.com.cn/",
        "id": 26,
        "language": "1",
        "name": "中国网——科学中国",
        "rulers": set(["http://science.china.com.cn/"]),
    },
    "huanqiu.com": {
        "url": "http://tech.huanqiu.com/",
        "id": 27,
        "language": "1",
        "name": "环球网——科技频道",
        "rulers": set(["http://tech.huanqiu.com/"]),
    },
    "chinanews.com": {
        "url": "http://it.chinanews.com/",
        "id": 28,
        "language": "1",
        "name": "中国网IT频道",
        "rulers": set(["http://it.chinanews.com/"]),
    },
    "gmw.cn": {
        "url": "http://tech.gmw.cn/",
        "id": 29,
        "language": "1",
        "name": "光明网——科技频道",
        "rulers": set(["http://tech.gmw.cn/"]),
    },
    "iresearch.cn": {
        "url": "http://www.iresearch.cn/",
        "id": 30,
        "language": "1",
        "name": "艾瑞网",
        "rulers": set(["http://www.iresearch.cn/"]),
    },
    "sina.com.cn": {
        "url": "http://blog.sina.com.cn/lm/tech/",
        "id": 31,
        "language": "1",
        "name": "IT_新浪博客",
        "rulers": set(["http://blog.sina.com.cn/lm/tech/"]),
    },
    "ciw.com.cn": {
        "url": "http://www.ciw.com.cn/",
        "id": 32,
        "language": "1",
        "name": "中国计算机行业网",
        "rulers": set(["http://www.ciw.com.cn/"]),
    },
    "eguan.cn": {
        "url": "http://www.eguan.cn/",
        "id": 33,
        "language": "1",
        "name": "易观网",
        "rulers": set(["http://www.eguan.cn/"]),
    },
    "ctocio.com.cn": {
        "url": "http://www.ctocio.com.cn/",
        "id": 35,
        "language": "1",
        "name": "IT专家网",
        "rulers": set(["http://www.ctocio.com.cn/"]),
    },
    "ccidcom.com": {
        "url": "http://www.ccidcom.com/",
        "id": 36,
        "language": "1",
        "name": "通信产业网",
        "rulers": set(["http://www.ccidcom.com/xinwenfenlei/",
                       "http://www.ccidcom.com/chanpinjishu/",
                       "http://www.ccidcom.com/hulianwang/",
                       "http://www.ccidcom.com/xingyebaogao/"]),
    },
    "sootoo.com": {
        "url": "http://www.sootoo.com/",
        "id": 37,
        "language": "1",
        "name": "速途网",
        "rulers": set(["http://ec.sootoo.com/",
                       "http://www.sootoo.com/content/"]),
    }
}
